name: Android Release APK (Signed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build web (Vite)
        run: npm run build

      - name: Add Android platform
        run: npx cap add android
        continue-on-error: true

      - name: Generate Android icons & splash
        run: npx @capacitor/assets generate --android

      - name: Sync web to Android
        run: npx cap sync android

      - name: Bump versionCode & versionName
        run: |
          VC=$((10000 + ${GITHUB_RUN_NUMBER}))
          VN=$(date +'%Y.%m.%d.%H%M')
          echo "Using versionCode=${VC}, versionName=${VN}"
          sed -i.bak 's/versionCode [0-9]\\+/versionCode '"${VC}"'/' android/app/build.gradle || true
          sed -i.bak 's/versionName "[^"]*"/versionName '"${VN}"'/' android/app/build.gradle || true
          grep -n 'versionCode\\|versionName' -n android/app/build.gradle || true

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      - name: Build Release (unsigned)
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Prepare keystore from secrets
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > hasaba.jks

      - name: Sign APK
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          BUILD_TOOLS=$(ls $ANDROID_SDK_ROOT/build-tools | sort -V | tail -n 1)
          UNSIGNED=android/app/build/outputs/apk/release/app-release-unsigned.apk
          OUT=app-release-signed.apk
          $ANDROID_SDK_ROOT/build-tools/$BUILD_TOOLS/apksigner sign \
            --ks hasaba.jks \
            --ks-key-alias "$ANDROID_KEY_ALIAS" \
            --ks-pass pass:"$ANDROID_KEYSTORE_PASSWORD" \
            --key-pass pass:"$ANDROID_KEY_PASSWORD" \
            --out "$OUT" "$UNSIGNED"
          $ANDROID_SDK_ROOT/build-tools/$BUILD_TOOLS/apksigner verify "$OUT"

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: hasaba-release-signed.apk
          path: app-release-signed.apk
